<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_home</name>
   <tag></tag>
   <elementGuidId>65a79cc0-14a0-4fca-bc79-52adfefe56a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/nav</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.woocommerce-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Home / Shop&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>751b905e-914d-46be-8ad3-0b5e65454163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-breadcrumb</value>
      <webElementGuid>5fdb559e-f188-44ec-afb5-643c84eef1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home / Shop</value>
      <webElementGuid>586796bc-9cde-473e-bc0e-a072e35ef705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/nav[@class=&quot;woocommerce-breadcrumb&quot;]</value>
      <webElementGuid>820d993a-89b2-4563-a920-f49450c524ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/nav</value>
      <webElementGuid>bb3a52a3-cc69-44e6-9b33-f246fc8c3eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹0.00'])[1]/following::nav[1]</value>
      <webElementGuid>95994a35-c97f-44bb-9ed4-aae591d05f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::nav[1]</value>
      <webElementGuid>7a598417-a888-4f54-9197-48e914914d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/preceding::nav[1]</value>
      <webElementGuid>7d5c54e8-5816-4d50-a3e8-fdec2bb59b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav</value>
      <webElementGuid>3d60bc14-477c-4999-bf22-177892c9e0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Home / Shop' or . = 'Home / Shop')]</value>
      <webElementGuid>dd2e4f9e-c137-4fed-9dd7-7b65e64ac200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
