<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_buku</name>
   <tag></tag>
   <elementGuidId>ff973e9b-e3cb-40f6-a404-676b35e91db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-181']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-shop_single.size-shop_single.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mastering HTML5 Forms&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b9796c1-bf2e-4481-beb3-d3cec8d0a9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>c934d360-98a7-46d6-8a05-777eb7d2b979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>a782ccf9-b2a3-4865-a594-c4b55733be2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-600x600.jpg</value>
      <webElementGuid>7d155a1e-c076-4a03-9d1d-f36cde3252dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-shop_single size-shop_single wp-post-image</value>
      <webElementGuid>6d1b7213-5959-4ab5-b6f1-46877d78e712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mastering HTML5 Forms</value>
      <webElementGuid>acc94104-6c7a-4caa-a380-aaaf4ba12158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c4de4872-2874-489d-9e6c-9ba0644891dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mastering HTML5 Forms</value>
      <webElementGuid>6bf179ae-ca48-44e6-be9c-87dbc0154994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-600x600.jpg 600w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-150x150.jpg 150w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-180x180.jpg 180w, https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-300x300.jpg 300w</value>
      <webElementGuid>9ddf3b2d-3f1f-498c-af3d-c990704df19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>3e8d6fb0-9c9a-4684-bac1-d8b7e808d245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-181&quot;)/div[@class=&quot;images&quot;]/a[@class=&quot;woocommerce-main-image zoom&quot;]/img[@class=&quot;attachment-shop_single size-shop_single wp-post-image&quot;]</value>
      <webElementGuid>905aed59-f8cf-48b4-91ea-e1f467907fe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-181']/div/a/img</value>
      <webElementGuid>dd73dbb9-d2e2-4fb1-a7ea-b360e3de501e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mastering HTML5 Forms']</value>
      <webElementGuid>9a9e92a3-fa94-4008-9892-fcdfc1da0074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>db2d7a2b-04cd-42ff-a408-bca17fc5dbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://practice.automationtesting.in/wp-content/uploads/2017/01/Mastering-HTML5-Forms-600x600.jpg' and @alt = 'Mastering HTML5 Forms' and @title = 'Mastering HTML5 Forms']</value>
      <webElementGuid>816382e6-fe6a-49d4-8aaf-27945965f92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
